# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countTransitions <- function(Obs, nStates) {
    .Call('Pkg_countTransitions', PACKAGE = 'Pkg', Obs, nStates)
}

getRegionCPP <- function(x, y) {
    .Call('Pkg_getRegionCPP', PACKAGE = 'Pkg', x, y)
}

checkRegionCPP <- function(x, y) {
    .Call('Pkg_checkRegionCPP', PACKAGE = 'Pkg', x, y)
}

simObs <- function(state0, nSteps, nStates, P) {
    .Call('Pkg_simObs', PACKAGE = 'Pkg', state0, nSteps, nStates, P)
}

