// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// countTransitions
List countTransitions(IntegerMatrix Obs, int nStates);
RcppExport SEXP Pkg_countTransitions(SEXP ObsSEXP, SEXP nStatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Obs(ObsSEXP);
    Rcpp::traits::input_parameter< int >::type nStates(nStatesSEXP);
    rcpp_result_gen = Rcpp::wrap(countTransitions(Obs, nStates));
    return rcpp_result_gen;
END_RCPP
}
// getRegionCPP
IntegerVector getRegionCPP(NumericVector x, NumericVector y);
RcppExport SEXP Pkg_getRegionCPP(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(getRegionCPP(x, y));
    return rcpp_result_gen;
END_RCPP
}
// checkRegionCPP
int checkRegionCPP(int x, int y);
RcppExport SEXP Pkg_checkRegionCPP(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(checkRegionCPP(x, y));
    return rcpp_result_gen;
END_RCPP
}
// simObs
IntegerMatrix simObs(IntegerVector state0, int nSteps, int nStates, NumericMatrix P);
RcppExport SEXP Pkg_simObs(SEXP state0SEXP, SEXP nStepsSEXP, SEXP nStatesSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type state0(state0SEXP);
    Rcpp::traits::input_parameter< int >::type nSteps(nStepsSEXP);
    Rcpp::traits::input_parameter< int >::type nStates(nStatesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(simObs(state0, nSteps, nStates, P));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"Pkg_countTransitions", (DL_FUNC) &Pkg_countTransitions, 2},
    {"Pkg_getRegionCPP", (DL_FUNC) &Pkg_getRegionCPP, 2},
    {"Pkg_checkRegionCPP", (DL_FUNC) &Pkg_checkRegionCPP, 2},
    {"Pkg_simObs", (DL_FUNC) &Pkg_simObs, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Pkg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
